name: C/C++ Build (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
